karma.conf.js, test/src/youbora.spec.js
=> chore: set default mocha timeout to 10000

src/youbora-adapter.js, src/youbora.js, test/src/youbora.spec.js
get player data from own config using kaltura/kaltura-player-js#30
=> chore: get player data from own config

package.json, src/youbora-adapter.js, src/youbora.js, test/src/youbora.spec.js
=> feat: change media

README.md
youbora configuration should be under `options`
=> chore: fix youbora structure in readme.md

.eslintrc.json, karma.conf.js, src/youbora.js, webpack.config.js
add export of name and version of library
=> feat: export name and version on module

webpack.config.js
align with the new bundles mechanism
=> feat: serve youbora as external bundle

karma.conf.js, src/youbora-adapter.js
checking for the severity of the error payload. If it's 2 (critical) then sending an error.
=> fix(FEC-8227): report only critical errors

package.json, src/adapter/adapter.js, src/adapter/ads/nativeads.js, src/youbora.js, test/src/youbora.spec.js, yarn.lock
Smartads v3 included: new ad metadata reported
Youboralib updated to 6.7.11
Added options to set external ads adapter
Unit test for the new feature
- [ x ] changes have been done against master branch, and PR does not conflict
- [ x ] new unit / functional tests have been added (whenever applicable)
- [ x ] test are passing in local environment
=> feat(FEC-10240): external ads adapter feature, lib update

.babelrc, .eslintignore, .eslintrc.json, .flowconfig, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .prettierignore, .travis.yml, README.md, karma.conf.js, package.json, scripts/after_deploy.sh, src/adapter/adapter.js, src/adapter/ads/nativeads.js, src/index.js, test/src/youbora.spec.js, webpack.config.js, yarn.lock
=> feat(FEC-10290): upgrade NPM packages

src/adapter/adapter.js
Initilize monitor playhead only for non-live content.
=> fix(FEC-10740): buffer begin reported from Youbora SDK on live dash content

package.json, test/src/youbora.spec.js, yarn.lock
=> feat(FEC-11283): upgrading the Youbora Library to 6.7.35

README.md
* direct to https
* the current link leads to outdated page
=> docs: set updated docs url

.travis.yml, src/adapter/adapter.js
Youbora lib doesnt send init in live so force it via options
=> fix(FEC-11644): rendition values are duplicated along with undefined data

docs/YouboraSessions.md
Inlcuded documentation to integrate youbora sessions mixing it with video analytics
=> Youbora sessions integration javascript

package.json, test/src/youbora.spec.js, yarn.lock
upgrade youbora plugin to fix an issue with parsing manifests with relative URLs.
=> feat(FEC-11725): upgrade Youbora plugin to version 6.7.42

src/adapter/ads/nativeads.js
fix incorrect path 
Solves FEC-11842
=> fix(FEC-11842): Youbora doesn't issue ad error

docs/YouboraSessions.md
=> docs: (FEC-12260) update youbora session doc

package.json, yarn.lock
=> fix(FEC-12112): upgrade "youboralib": "6.8.22"

src/adapter/adapter.js
=> fix(FEC-13038): Add image track type only if player sources with image is populated

src/adapter/adapter.js
=> fix(FEC-13038): fix wrong media type reported as Image  on change media cont.
